### ISSUE TITLE
racon and pilon

### ISSUE THREAD

**Issue by flystar233** [adigenova/wengan#11]
When I finished the assembly with wengan, the result was very good. and busco scored was 90%. 
So, I used racon software polish my genome, the score dropped to 63%. 
May I ask if racon and pilon are not used?

**Comment by adigenova** [comment]
Hi, 
Long-read polishing (racon) is not recommended for Wengan assemblies.  For the moment, I recommend short-read polishing only, because the majority of Wengan consensus errors are small indels (< 3bp) located in sequences called from long-read only. Thus, short-read polishing may be sufficient to get rid of such errors. You can polish with Pilon if your genome is small or medium (< 300Mb), and NTedit (3 rounds) for a large genome (>300Mb).  

Best,
Alex
