### ISSUE TITLE
What's the difference of GPolished and SPolished

### ISSUE THREAD

**Issue by billzt** [adigenova/wengan#13]
I'm doing a hybrid assembly of ~ 2G genome. When I saw a file called `foo.GPolished.asm.wengan.fasta` generated, I thought all the assembly steps have been finished (as I can't see the `liger` process using the `top` command) and then move all the files to other directories.

In fact, after referring the demo dataset, I found I was wrong. The `SPolished` rather than `GPolished ` should be the final result.

(1) What's the difference of GPolished and SPolished? I suggest to add this as a notice in the README.
(2) Since this pipeline usually lasts for 1-2 days, are there any methods to resume if it were stopped in accident?

**Comment by adigenova** [comment]
## (1) What's the difference of GPolished and SPolished? I suggest to add this as a notice in the README.
Wengan implements two polishing methods, one based on Graph (GPolished) and a second one based on sequence pairwise alignments (SPolished). The Gpolished is applied before SPolished.
See #3 
I'll add this to the documentation. 
### Since this pipeline usually lasts for 1-2 days, are there any methods to resume if it were stopped in accident?
Yes, the pipeline execution is controlled by make tool (see file prefix.mk), thus it can restart from the last successful built target.
