### ISSUE TITLE
how can i set the output directory?

### ISSUE THREAD

**Issue by koujiaodahan** [adigenova/wengan#28]
1.As the title, how can i set the ouput directory?
2.should i run some correlation program before running the software when input ONT reads?

**Comment by adigenova** [comment]
Hi,

At the moment there is no option to specify the output directory and by default is the one from where wengan is launched. I'll add this option in near future.
 I do not fully understand the second question, but wengan expects raw ONT reads.
Best
Alex

**Comment by koujiaodahan** [comment]
ok, thanks for your reply!

**Comment by koujiaodahan** [comment]
with MGI reads and ONT reads ,should i run wenganD to achieve the best assembly output if I have sufficient computing resouce?  In generally,running default wenganA mode is ok considering the running efficiency?

**Comment by koujiaodahan** [comment]
![image](https://user-images.githubusercontent.com/26478793/98634966-94b81000-233d-11eb-9dfa-0ec0b5ac119a.png)
I run quast to evaluate the  default wengan  mode results ,but it is very poor compared to your article .the sequencing depth both is 60X

**Comment by adigenova** [comment]
Hi, 

The NG50 with 60X should be higher than 5Mb for a Human genome with WenganA (>10Mb). 

What is the read length of the MGI reads? and what is the N50 of the Nanopore reads?

In our manuscript, we used MGI reads of 2x150bp at 50X coverage and ONT reads with N50 ~19kb at 20-30X coverage The resulting assemblies reach NG50s > 10Mb (~14Mb for WenganA and ~19Mb for WenganD).

**Comment by koujiaodahan** [comment]
Hi，i try the wenganA，but the final fasta is just 2Mb,it is unmornal,maybe is there some bug when i installed?But its ok when run wenganM.here is my command:
perl ~/Assembly_wengan/wengan-v0.2-bin-Linux/wengan.pl -M 1000 -x ontraw -a A -s mgi_r1,$mgi_r2 -l $ontfq -p prefix -t 20 -g 3000 2>prefix.err

i have compressed the error the log file as follows,please check it:
[err.tar.gz](https://github.com/adigenova/wengan/files/5541299/err.tar.gz)
[log.tar.gz](https://github.com/adigenova/wengan/files/5541300/log.tar.gz)

I'm looking forwward to your advice for the bug, thanks!

> Hi,
> 
> The NG50 with 60X should be higher than 5Mb for a Human genome with WenganA (>10Mb).
> 
> What is the read length of the MGI reads? and what is the N50 of the Nanopore reads?
> 
> In our manuscript, we used MGI reads of 2x150bp at 50X coverage and ONT reads with N50 ~19kb at 20-30X coverage The resulting assemblies reach NG50s > 10Mb (~14Mb for WenganA and ~19Mb for WenganD).

**Comment by adigenova** [comment]
Hi, 
I took a look to the Abyss short-read assembly and it seem that it run as usual, however the resulting short-read assembly is only 2Mb long with an N50 of 272bp. Abyss generates N50 around 9-15Kb and assembles 2.75-2.85 Gb of sequence for human genomes. So, this problem affect all subsequent wengan steps. 

To me it seem that there are some problems with the short-read data,

1) I see that the length of your short-reads is 2x100bp. So, this is one problem for abyss, because we used k=96  that is optimized for 2x150bp reads, with shorter reads you should reduce the size of K (i.e 61 or 75 as maximum).  I recommend you work a bit on the short-read assembly first and then after reaching a good N50 (N50 6-9kb) give it as input to Wengan using the -c option.

2) In our paper we worked only with 2x150 or 2x250bp short-reads. Thus for 2x100bp I would expect more fragmented short-read assemblies and therefore some wengan parameters should be modified (i.e -M 1000). 

3) If you have a machine with good memory, you can try WenganD with your raw 2x100bp (I see that your reads are named "clean"). Usually in genome assembly we do not remove low quality bases (trim), because short-read assembler have algorithms to deal with sequencing errors. 

A more straight forward alternative is to rerun WenganM with the option -M 1000 (default is -M 2000), this would help a bit with the fragmented short-read assembly generated from 2x100bp reads.

Best,
 
Alex

**Comment by koujiaodahan** [comment]
Thanks for your reply!
According to your advice:
     1) can i run the SOAPdenovo as  short-read assembly method ?
     2) i will set -M 1000 for all wengan mode
     3) i will try wenganD ,  and I run filtering software, not only to filter low-quality reads but also to filter adapter

**Comment by adigenova** [comment]
1) We currently support Minia3(WenganM), Abyss(WenganA) and DiscovarDenovo(WenganD).  However, you can try SOAPdenovo and give its result to WenganA using the -c parameter.
2) Yes if the assembly is fragmented that option help, but the minimum is -M 1000. 
3) DiscovarDenovo will stop if there are reads shorter than 65 base pairs in your fastq files.

Best,
Alex
