### ISSUE TITLE
core dumped at liger step

### ISSUE THREAD

**Issue by minky** [adigenova/wengan#37]
Hello,

I had problem in running wengan at liger step, it seems that the program can't handle with ambiguous nucleotides, but I'm not sure.

here is the reported error in log files:
(core dumped) /home/minky/Software/wengan-v0.2-bin-Linux/bin/liger --mlp 10000 -t 64 -c asm8.MBC7.msplit.fa -l longreads.asm81.fa -d asm8.MBC7.msplit.cov.txt -p asm8 -s asm8.sams.txt 2> asm8.liger.err > asm8.liger.log

In asm8.liger.err:
terminate called after throwing an instance of 'std::invalid_argument'
  what():  invalid DNA base found in DnaBitset class

In the last lines of asm8.liger.log:
Warning:Invalid DNA base found :N
Warning: Changing base to A

Any suggestions how to solve the issue?

Best,
Minky

**Comment by adigenova** [comment]
Hi Minky, 

Yes, you are right, liger cannot handle ambiguous nucleotides, are you running liger independently? I mean without using the Wengan pipeline. I ask this because at earlier steps wengan remove the ambiguous bases from the short-read contigs, thus the only source of ambiguous letters can be the long-reads, if that is the case, you can replace the N bases on your long-reads using my fork of the seqtk program, you have to run the following command:

```
#compilation 
git clone https://github.com/adigenova/seqtk.git
cd seqtk; make
#this command will replace all N character by A, the input can be in fasta or fastq format.
./seqtk iupac2basesA test.fa
```

After running the above, you will get the long-read sequences free of N, alternative, you can split the long-read sequence using the "cutN" program of seqtk, but I think that the first idea might be better for you unless you have plenty of N letters.
The program report the number of bases changed at the end (stderr). After fixing the long-read file you can rerun wengan. 

Best,
Alex

**Comment by minky** [comment]
Hi Alex,

Thanks a lot. The problem was solved after replacing N with A. I didn't run liger independently, but I applied the mode of "wengan.pl -x pacraw -a A" with input contig assembly from the platanus software.

Indeed the N bases are from the long-reads. There are 4M of Ns out of ~5 Gb pacbio data (seems not too many?). I see that Wengan was designed for human genome. I'm working with a plant genome with complex repeat regions like Arabidopsis. The genome size of my plant is ~250m and the pacbio long-reads covered ~20X of the genome. Wengan pipeline increased the contig N50 from 53k to 92k. I think this is already a great improvement.

Best,
Minky

**Comment by adigenova** [comment]
Hi Minky, 
It seems that you can improve a bit more the result by using WenganD with the raw data (I mean without starting from the Platanus assembly). As you have 20X of long-read coverage you might set the -N parameter to -N 3 (def is 5), there are additional optimizations described on #38 #35.
Best,
Alex
