### ISSUE TITLE
Parameter recommendation for low coverage Nanopore read ( 5X; N50 ~ 5kb)

### ISSUE THREAD

**Issue by hxg2760** [adigenova/wengan#38]
Hello, 

I am hoping to use wengan as an alternative to MaSurCA. However, my initial assembly using 50X PCR-free illumina ( 2x 150bp) and 5x nanopore has been somewhat suboptimal using the default v0.2 setting. Specifically, the inclusion of long read data didn't improve the assembly significantly. The current N50 is around 8kb using short read alone and still hovering around 8kb with long read inclusion (abyss). 

Going through the discussion, i can see that reducing the -N to 2 is helpful to tackle low coverage long read. 
Is there additional parameter that can be tweaked to account for shorter Nanopore read length? I see that the default assume a read length distribution of 15kb. 

A combination of pore block and old DNA led to the reduced nanopore yield and read length unfortunately. 

Regards, 
Ming

**Comment by adigenova** [comment]
Hi Ming, 
To overcome low  long-read coverage and lower N50 (5bk) of your ONT data, you might try the following options:

1. Use WenganD because it uses better the short-read data and with low coverage this mode generates the best results (You need a high memory machine, for a 3Gb genome it use ~600Gb of RAM).
2. Set  -N 2 and -P 8000, both options will keep more joins while validating the backbone. 
3. Set the insert sizes for synthetic libraries as follows: 
"-i 500,1000,2000,3000,4000,5000,6000,7000,8000,9000,10000,11000,12000,13000,14000,15000,20000"

Hope that this tunning will improve the result.
Best,
Alex

**Comment by adigenova** [comment]
Feel free to reopen if you have further questions.
Best,
Alex

**Comment by tim-oconnor** [comment]
I'd be interested to hear if this worked for you, Ming. I have very similar data and am shopping around for the best approach to assemble them.

Thanks,
Tim

**Comment by hxg2760** [comment]
It's alright but to avoid a life of regret - best to generate more long
read than living with the low coverage.

Han Ming GAN, PhD
CSO
*GeneSEQ Sdn Bhd*
57-59, Jalan Adenium 2g/6, Bukit Beruntung,
48300 Rawang, Selangor, Malaysia
HP: 019-9155980

**Comment by tim-oconnor** [comment]
Thanks Ming.
Unfortunately I have no choice (rare museum samples with no additional DNA available), so I'll have to make the best of it. I appreciate your reply.
Best,
Tim
