### ISSUE TITLE
Possibility of integrating Megahit as a new member for SR assembly?

### ISSUE THREAD

**Issue by hxg2760** [adigenova/wengan#42]
Just came across some very interesting findings based on N=1 of a fish genome (another one now assembling ). The N50 of megahit looks pretty good compared to Abyss2 for this sample. N50 9k (abyss2) vs N50 42k (megahit) . I wonder if this megahit can be the "intermediate" between the fast/memory-saving Abyss2/MINION and the all-mighty but memory greedy Discovar?

In other words, i wonder if you will be happy to do some quick benchmark using megahit as the contigger

Regards, 
Ming

**Comment by adigenova** [comment]
Hi Ming, 

I have not tested megahit, but It is possible to give wengan other short-read assemblies using the -c option in combination with the mode -a D or -a A. if you really trust the contigs is better to choose the -a D (Disco) mode because the error-correction of short-read contigs is less aggressive than with the -a A (abyss).  Let me know if you have issues integrating the megahit contigs using the above options. Unfortunately, I'm a bit short of time nowadays to formally test this assembler, but  Wengan will error-correct and validate the megahit assembly, thus you should be safe.

best,
Alex

**Comment by hxg2760** [comment]
Hi Alex, 

Just to clarify (and i would test this tomorrow morning anyway) , the -a D or -a A when given the -c option, will not be a full-fledge re-assembly right?  -a D freaks me out abit. I love the fact that Wengan will error-correct and validate assembly. It is really cool. Will provide a report of Abyss vs Megahit wengan assembly in the next few days so keep this issue open for awhile until i get back. 

Regards, 
Ming

**Comment by adigenova** [comment]
Hi Ming, 

The -c option allows wengan to skip the short-read assembly, thus the assembly start error-correcting the short-read contigs (split of contigs not supported by pair-end). Then, the difference between -a D and -a A is that Discovar is more accurate than Abyss and therefore the error-correction is less aggressive for -a D. So, if you think that megahit generates accurate contigs, then use -a D otherwise -a A. Since the short-read assembly is skipped, both modes should use low memory (40-80 Gb).

Best, 
Alex

**Comment by hxg2760** [comment]
Hi Alex, 

Did a megahit for another samples - the N50 gain is still better than Abyss2 (8kb megahit vs 5kb Abyss2, but not as impressive as the previuos sample). 

When i used the assembly as the input for wengan, the assembly statistic is increased by around 10kb. from N50 of 35.8kb for Abyss2-based to N50 of 46.3kb megahit-based. I wouldn't say that it is very impressive but it does look like an improvement to me. Furthermore, it completed the assembly in less than 24 hours. 

Regards, 
Ming
