### ISSUE TITLE
Not in gzip format

### ISSUE THREAD

**Issue by shaobinzhong** [adigenova/wengan#52]
Hello,

I tried to assembly a fungal genome with illumina and ont data using the following command:

wengan.pl -x ontraw -a M -s A1.illumina.fwd.fastq, A1.illumina.rev.fastq -l ont_trimQ10.fq -p asm1 -t 8 -g 36

But I got the following error message:

gzip: A1.illumina.fwd.fastq: not in gzip format
Illegal division by zero at /gpfs1/projects/shaobin.zhong/wengan/wengan-v0.2-bin-Linux/perl/Wengan/Reads.pm line 150.

I have the sequence reads in fastq format. Does Wengan accept fastq files?

Thanks for your help!

Shaobin

**Comment by adigenova** [comment]
Dear Shaobin,

Thanks for your message, it seems that the error happens because your fastq files are not compressed with gzip.
Wengan expects fastq files compressed with gzip, thus before running Wengan you should compress all your sequence files with gzip (i.e gzip  A1.illumina.fwd.fastq).

Best regards,
Alex

**Comment by shaobinzhong** [comment]
Thank you, Alex. After I converted the fastq files into fastq.gz files, the program run well. Thanks again for your help! Shaobin
