### ISSUE TITLE
 No rule to make target 'asm.MBC1.msplit.cov.txt', needed by 'asm1.fa'.

### ISSUE THREAD

**Issue by sigau** [adigenova/wengan#53]
Hi !
First thanks for the tool !

So I was trying to assemble a genome using wengan D using both short-reads and long-reads on a computer with 1To of ram and 45 cpu.

At one moment I get this error (a file that is needed for the creation of another one ) :
`
make: *** No rule to make target 'Proasellus_coiffaiti_HYB_wangan_D.MBC1.msplit.cov.txt', needed by 'longreads.Proasellus_coiffaiti_HYB_wangan_D1.fa'.  Stop.`

So I don't really know what I can do to correct this.

Thanks in advance 

here the error, script, and make files : 

[assembly_wengan_D_PC.e.txt](https://github.com/adigenova/wengan/files/7194354/assembly_wengan_D_PC.e.txt)

[assembly_wengan_PC.sh.txt](https://github.com/adigenova/wengan/files/7194356/assembly_wengan_PC.sh.txt)

[Proasellus_coiffaiti_HYB_wangan_D.mk.txt](https://github.com/adigenova/wengan/files/7194387/Proasellus_coiffaiti_HYB_wangan_D.mk.txt)

**Comment by adigenova** [comment]
Hi, 
It seem that a pre-requisite failed while running the pipeline, can you share please the content of the file "Proasellus_coiffaiti_HYB_wangan_D.Disco_denovo.log"?, This file is the output of the short-read assembler which is the first step performed by the pipeline.
best
Alex

**Comment by adigenova** [comment]
Feel free to reopen if you can share some additional information.
Best
Alex

**Comment by sigau** [comment]
Hi ,
sorry we got hard time with our cluster and I could get back the log before you close the issue. Here the log you were asking for .
Again sorry for the delay
[Proasellus_coiffaiti_HYB_wangan_D_porechop_3kb.Disco_denovo.log](https://github.com/adigenova/wengan/files/7432325/Proasellus_coiffaiti_HYB_wangan_D_porechop_3kb.Disco_denovo.log)
.

**Comment by adigenova** [comment]
Hi sigau, 

The error indeed is a small bug due to a regular expression, if the prefix constains the "fa" the generation of the makefile fail due to the following regex in the wengan code:
[IM.pm line 107](https://github.com/adigenova/wengan/blob/b71c72d4e3f7c9c8e0ca6314bfc9e1c44a839e4d/perl/Wengan/Chimeric/IM.pm#L107)
```
 $target=~s/.fa/.cov.txt/;
```
which should be :
```
$target=~s/\.fa/\.cov.txt/;
```
I will the update code in the next release, for the moment you should avoid "fa" in the prefix  (-p), thus you can replace "Proasellus_coiffaiti_HYB_wangan_D" by "PCHY_WD" and should do the trick.

Best,
Alex

**Comment by sigau** [comment]
Thanks,
I will try this !

Best,
