### ISSUE TITLE
Pre-generated short read genome input

### ISSUE THREAD

**Issue by Dikaryotic** [adigenova/wengan#9]
Hiya, 

I've been having a play with Wengan and it assembled one of my datasets fantastically! However, my second data set isn't quite as good quality and didn't perform well with the Minia assembler. I had some troubles running the Abyss2 assembler through Wengan, however I did manage to assemble a contig level assembly seperately. However I then encountered some weird issues when trying to input that into Wengan with the -C and -a A options. In parallel to that, I already have some short read assemblies created through SPAdes. Could you shed a little light about whats happening when inputting a pre-constructed assembly via -C so that I can maybe trouble shoot whats causing my errors? Would it be possible for me to use my SPAdes assemblies at all? It's my standard go-to assembler for my genomes, it's nowhere near as fast as Minia, but produces more contiguous genomes with better BUSCO scores. For example, the Minia-Wengan assembly came out with a low 70% complete BUSCO and was half the size it should be, in contrast to a solid mid ~96% complete via SPAdes. 

Otherwise, Wengan is fantastic! It smashed out a better genome than my Canu + RaconX2 + PilonX2 genome in a fraction of the time!

**Comment by adigenova** [comment]
Hi Chris:
## Could you shed a little light about whats happening when inputting a pre-constructed assembly via -C so that I can maybe trouble shoot whats causing my errors? 
the -c option allows you to skip the short-read assembly, but you have to provide also the short-reads that were used to build the short-read assembly. The reads are used to  identify and error-correct chimeric short-read contigs. An example should  look like this one:

``` wengan.pl -x ontraw -a D -s fwd.fastq.gz,rev.fastq.gz -l ont.fastq.gz -p asm8 -t 20 -g 3000 -c contigs.disco.fa ```

Then, wengan map the short-reads to the given contigs and used intervalmiss to validate each of the contig bases, then use the validated short-read contigs to build the assembly backbone.

## Would it be possible for me to use my SPAdes assemblies at all?
I have not tested all the short-read assemblers but Spades is a good one. If you trust your short-read assembly then used -a D pipeline. That will map the short-reads to the given assembly and then intervalmiss is called with less aggressive parameters requiring only 1 fragment to trust the contigs bases (by default is 5 fragments), then the assembly continues as normal. You can give the scaffolds produced by the Spades assembler, then wengan get the contigs from that. Take a look at the ***prefix.mk*** file, which is a makefile that contains all the commands that wengan execute to build the hybrid assembly.

let me know how it goes and thanks for the positive comments.

best,
Alex

**Comment by Dikaryotic** [comment]
Awesome, thanks for that! I had been using code pretty much exactly as youve suggested. I''ll try dig out the error and see what you think, I'm just at conference on a work laptop so I'll see how I go. Good to know about using the -a D pipeline for my SPAdes assemblies, I'll try that when I can.

**Comment by adigenova** [comment]
Ok, great!!! take a look at the *.err or *.log files. 
best,

Alex

**Comment by Dikaryotic** [comment]
Heya, 

I just had a go running this: 
./wengan.pl -x ontraw -a D -c HKGP-Spades-scaffolds.fasta -s Hericium_trimmed_1.fastq.gz,Hericium_trimmed_2.fastq.gz -l PC-HKGP-HAC-Guppy3.3.fastq.gz -g 50 -p HKGP-Spades -t 30

The slurm output threw this result:
/bin/sh: line 1: 164892 Floating point exception(core dumped) /scale_wlg_nobackup/filesets/nobackup/landcare00072/Genome/Programs/wengan/bin/intervalmiss -d 1 -t 30$
make: *** [HKGP-Spades.MBC1.msplit.fa] Error 136

I dug a little deeper and it looks like the fms step is being funky, find the output from the *.fms.err file

LOG: Mapping mode =shortr H=0 k=21 w=10 L=2000 l=250 q=20 m=150 c=50 r=50000 t=30 o=FM I= s=1
Building contig index
[M::mm_idx_gen::1575246902.326*0.00] collected minimizers
[M::mm_idx_gen::1575246902.328*0.00] sorted minimizers
[M::mm_mapopt_update::1575246902.328*0.00] mid_occ = 1000
[M::mm_idx_stat] kmer size: 21; skip: 10; is_hpc: 0; #seq: 0
[M::mm_idx_stat::1575246902.328*0.00] distinct minimizers: 0 (-nan% are singletons); average occurrences: -nan; average spacing: -nan
Index construction time: 0.010000 seconds for 0 target sequence(s)
Average insert size 0 std 0 [-10 outlayers]
Thread_info:Partial TOTAL_PAIRS=49999 MAPPED_PAIRS=0  RL=55 MINQ=20 KS=21 MW=150 PRESCUE=0 RESCUE=0

For some reason none of the pairs are being mapped onto it. Thoughts? Any other info I can provide?

**Comment by Dikaryotic** [comment]
Yo, I tracked it back to the version of seqtk I had, I initially didn't realize it was bundled and went and got the newest version from Github. Going and replacing that version with the bundled one looks to have solved the problem. Thanks for all the help.

**Comment by adigenova** [comment]
The seqtk version that wengan use is a fork of the original seqtk and include additional functions (commits), the original does not have these additional functions. So, better to use my forked seqtk.  

Best, 
Alex
